# Generated by Django 5.0.4 on 2024-04-04 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('codedept', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nomdept', models.CharField(blank=True, max_length=100, null=True)),
                ('descriptiondept', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('cin', models.IntegerField(primary_key=True, serialize=False)),
                ('nomemp', models.CharField(blank=True, max_length=100, null=True)),
                ('prenomemp', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissanceemp', models.DateField(blank=True, null=True)),
                ('sexeemp', models.CharField(blank=True, max_length=1, null=True)),
                ('emailemp', models.CharField(blank=True, max_length=100, null=True)),
                ('telephoneemp', models.CharField(blank=True, max_length=20, null=True)),
                ('adresseemp', models.TextField(blank=True, null=True)),
                ('titreemp', models.CharField(blank=True, max_length=100, null=True)),
                ('salaireemp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('datedebuttravail', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Travailler',
            fields=[
                ('cin', models.OneToOneField(db_column='cin', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gestionemploye.employe')),
                ('datedebuttravail', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'travailler',
                'managed': False,
            },
        ),
    ]
